### ISSUE TITLE
Availability of the 4.74 release (or previous release with Visual Studio Projects)

### ISSUE THREAD

**Issue by smorin-primero** [datareel/datareel#1]
Hi

I'm looking for the 4.74 release. I'm trying to build datareel for Windows with Visual Studio, but as far as I can see, the last release supporting Windows was the 4.74 release.

I can't seem to find it on the datareel.com website, and the github repository starts with the 5.01 version.

Your help would be greatly appreciated.

Thanks

**Comment by datareel** [comment]
Hello,

When the old Web site was moved to github, I didn't copy over the previous releases. I'll get the previous release published as soon as possible and follow-up on this thread with the repo link.

Thank for your patience.

**Comment by datareel** [comment]
DataReel version 4.74/4.75 is available on github in the following repo:

https://github.com/datareel/datareel_4_visual_studio

This repo includes all the MSCV makefiles and DLL build. In this repo we can remove the legacy UNIX builds and add the Visual Studio project files.

**Comment by smorin-primero** [comment]
Thank you very much
